// Default workout plan, transcribed exactly as provided.
// No invented exercises or numbers — this is the source of truth for seeding.

const workoutDays = [
  {
    dayNumber: 1,
    name: 'Pull A',
    isRestDay: false,
    exercises: [
      { category: 'Compound', name: 'Deadlift', sets: 3, repsRange: '5-6' },
      { category: 'Back', name: 'Pull-up', sets: 3, repsRange: '8-10' },
      { category: 'Back', name: 'Lat Pulldown', sets: 3, repsRange: '10-12' },
      { category: 'Back', name: 'Seated Cable Row', sets: 3, repsRange: '10-12' },
      { category: 'Back', name: 'One-arm Dumbbell Row', sets: 3, repsRange: '10-12' },
      { category: 'Back', name: 'Straight-arm Lat Pulldown', sets: 3, repsRange: '12-15' },
      { category: 'Rear Delts', name: 'Bent Over Lateral Raise', sets: 3, repsRange: '12-15' },
      { category: 'Biceps', name: 'Standing Dumbbell Curl', sets: 3, repsRange: '10-12' },
      { category: 'Biceps', name: 'Standing Hammer Curl', sets: 3, repsRange: '10-12' },
      { category: 'Forearms', name: 'Wrist Curl', sets: 2, repsRange: '15' },
      { category: 'Forearms', name: 'Reverse Wrist Curl', sets: 2, repsRange: '15' },
    ],
  },
  {
    dayNumber: 2,
    name: 'Push A',
    isRestDay: false,
    exercises: [
      { category: 'Chest', name: 'Incline Dumbbell Press', sets: 4, repsRange: '8-10' },
      { category: 'Chest', name: 'Bench Press', sets: 4, repsRange: '8-10' },
      { category: 'Chest', name: 'Incline Cable Fly', sets: 3, repsRange: '12' },
      { category: 'Chest', name: 'Decline Cable Fly', sets: 3, repsRange: '12' },
      { category: 'Shoulders', name: 'Dumbbell Lateral Raise', sets: 3, repsRange: '15' },
      { category: 'Shoulders', name: 'Cable Upright Row', sets: 3, repsRange: '10' },
      { category: 'Traps', name: 'Barbell Shrugs', sets: 3, repsRange: '12' },
      { category: 'Triceps', name: 'Rope Pushdown', sets: 3, repsRange: '12' },
      { category: 'Triceps', name: 'Seated EZ Bar Triceps Extension', sets: 3, repsRange: '10' },
      { category: 'Triceps', name: 'Bench Dips', sets: 2, repsRange: 'Failure' },
    ],
  },
  {
    dayNumber: 3,
    name: 'Legs A + Abs',
    isRestDay: false,
    exercises: [
      { category: 'Legs', name: 'Squat', sets: 4, repsRange: '8' },
      { category: 'Legs', name: 'Angled Leg Press', sets: 3, repsRange: '12' },
      { category: 'Legs', name: 'Leg Extension', sets: 3, repsRange: '15' },
      { category: 'Legs', name: 'Stiff-legged Deadlift', sets: 3, repsRange: '10' },
      { category: 'Legs', name: 'Standing Barbell Calf Raise', sets: 4, repsRange: '15' },
      { category: 'Abs', name: 'Hanging Knee Raise', sets: 3, repsRange: '15' },
      { category: 'Abs', name: 'Cable Crunch', sets: 3, repsRange: '15' },
      { category: 'Abs', name: 'Hanging Knee Oblique Raise', sets: 3, repsRange: '12' },
      { category: 'Abs', name: 'Barbell Rollout', sets: 3, repsRange: '10' },
    ],
  },
  {
    dayNumber: 4,
    name: 'Pull B',
    isRestDay: false,
    exercises: [
      { category: 'Back', name: 'Chin-up', sets: 3, repsRange: '8-10' },
      { category: 'Back', name: 'V-Bar Lat Pulldown', sets: 3, repsRange: '10-12' },
      { category: 'Back', name: 'Bent Over Row', sets: 4, repsRange: '8-10' },
      { category: 'Back', name: 'Seated Cable Row', sets: 3, repsRange: '10-12' },
      { category: 'Back', name: 'Straight-arm Lat Pulldown', sets: 3, repsRange: '12-15' },
      { category: 'Rear Delts', name: 'Bent Over Lateral Raise', sets: 3, repsRange: '15' },
      { category: 'Biceps', name: 'Incline Dumbbell Curl', sets: 3, repsRange: '10-12' },
      { category: 'Biceps', name: 'Preacher Curl', sets: 3, repsRange: '10-12' },
      { category: 'Forearms', name: 'Wrist Curl', sets: 2, repsRange: '15' },
      { category: 'Forearms', name: 'Reverse Wrist Curl', sets: 2, repsRange: '15' },
    ],
  },
  {
    dayNumber: 5,
    name: 'Push B',
    isRestDay: false,
    exercises: [
      { category: 'Chest', name: 'Incline Press Machine', sets: 4, repsRange: '8-10' },
      { category: 'Chest', name: 'Dumbbell Press', sets: 4, repsRange: '8-10' },
      { category: 'Chest', name: 'Dumbbell Fly', sets: 3, repsRange: '12' },
      { category: 'Chest', name: 'Parallel Bar Dips', sets: 3, repsRange: '10-12' },
      { category: 'Shoulders', name: 'Single Arm Cable Lateral Raise', sets: 3, repsRange: '15' },
      { category: 'Shoulders', name: 'Bent Over Lateral Raise', sets: 3, repsRange: '15' },
      { category: 'Traps', name: 'Dumbbell Shrugs', sets: 3, repsRange: '12' },
      { category: 'Triceps', name: 'Reverse Pushdown', sets: 3, repsRange: '12' },
      { category: 'Triceps', name: 'One-arm Reverse Pushdown', sets: 3, repsRange: '12' },
      { category: 'Triceps', name: 'Rope Pushdown', sets: 2, repsRange: 'Failure' },
    ],
  },
  {
    dayNumber: 6,
    name: 'Legs B + Abs',
    isRestDay: false,
    exercises: [
      { category: 'Legs', name: 'Sumo Squat', sets: 4, repsRange: '10' },
      { category: 'Legs', name: 'Walking Lunges', sets: 3, repsRange: '12 Each Leg' },
      { category: 'Legs', name: 'Romanian Deadlift', sets: 3, repsRange: '10' },
      { category: 'Legs', name: 'Seated Leg Curl', sets: 3, repsRange: '12' },
      { category: 'Legs', name: 'Seated Calf Raise', sets: 4, repsRange: '15' },
      { category: 'Abs', name: 'Roman Chair Leg Raise', sets: 3, repsRange: '15' },
      { category: 'Abs', name: 'Bicycle Crunch', sets: 3, repsRange: '20' },
      { category: 'Abs', name: 'Russian Twist', sets: 3, repsRange: '20' },
      { category: 'Abs', name: 'Plank', sets: 3, repsRange: '45-60 Seconds' },
    ],
  },
  {
    dayNumber: 7,
    name: 'Rest Day',
    isRestDay: true,
    exercises: [],
    recoveryTips: [
      'Prioritize 7-9 hours of sleep to support muscle recovery.',
      'Keep daily activity light — walking is fine, avoid heavy training.',
    ],
    stretchingSuggestions: [
      'Full-body static stretching, 5-10 minutes.',
      'Foam roll major muscle groups worked earlier in the week.',
    ],
    hydrationReminder: 'Drink water consistently through the day, even on rest days.',
  },
];

module.exports = { workoutDays };
